### ISSUE TITLE
FOTA  not working with release SDK 3.0

### ISSUE THREAD

**Issue by Dipendra77** [espressif/ESP8266_NONOS_SDK#305]
Why does calling system_upgrade_start()  cause compilation error saying,  no reference defined for system_upgrade_start function ?

**Comment by davydnorris** [comment]
Silly question but you included libupgrade in your library list?
